package net.simplyanalytics.enums;

import java.util.ArrayList;
import java.util.List;

public enum DataDocumentationLinkEnum {

    SIMPLYANALITICS_US_VARIABLES("SimplyAnalytics U.S. variables",
            "https://assets.simplyanalytics.com/documents/SimplyAnalytics_Variable_List_2021.pdf",
            "https://assets.simplyanalytics.com/documents/SimplyAnalytics_Variable_List_2021.pdf",
            "Variables"),
    SIMPLYANALITICS_CANADIAN_VARIABLES("SimplyAnalytics Canadian variables",
            "https://assets.simplyanalytics.com/documents/SimplyAnalytics_Canada_Variable_List.pdf",
            "https://assets.simplyanalytics.com/documents/SimplyAnalytics_Canada_Variable_List.pdf",
            "Variables"),

    //EASI category
 /* EASI_METHODOLOGY("EASI Methodology: Demographics, Related Data, and Life Stage Clusters",
          "https://assets.simplyanalytics.com/documents/EASI_Methods__-_2018_Updates.pdf",
          "https://assets.simplyanalytics.com/documents/EASI_Methods__-_2018_Updates.pdf",
          "EASI"),
  EASI_LIFE_STAGE_CLUSTERS("EASI Life Stage Clusters",
          "https://assets.simplyanalytics.com/documents/EASI_Life_Stages_Detailed_2019.pdf",
          "https://assets.simplyanalytics.com/documents/EASI_Life_Stages_Detailed_2019.pdf",
          "EASI"),
  EASI_2010_CENSUS_WHITE_PAPER("2010 Census White Paper - Creating Block Group Benchmarks",
          "https://assets.simplyanalytics.com/documents/EASI_2010_Census_Update_White_Paper.pdf",
          "https://assets.simplyanalytics.com/documents/EASI_2010_Census_Update_White_Paper.pdf",
          "EASI"), easi data is no longer avilable*/

    //ENVIRONICS
    ENVIRONICSANALYTICS_WEBSITE("www.environicsanalytics.ca",
            "http://www.environicsanalytics.ca",
            "http://www.environicsanalytics.ca",
            "Environics Info"),
    VARIABLE_LIST_SOURCE("here",
            "https://environicsanalytics.com/en-ca/resources/product-documentation/variables",
            "https://environicsanalytics.com/en-ca/resources/product-documentation/variables",
            "Environics Info"),
    MORE_DATABASE("here",
            "https://community.environicsanalytics.com/hc/en-us/sections/360006982352-Canadian-Data",
            "https://community.environicsanalytics.com/hc/en-us/sections/360006982352-Canadian-Data",
            "Environics Info"),

    //ENVIRONICS - CENSUS_PLUS
    CENSUSPLUS_2016_VARIABLES("CensusPlus 2016 Variables",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2016_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2016_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_2016_RELEASE_NOTES("CensusPlus 2016 Release Notes",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2016_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2016_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_2016_TECHNICAL_DOCUMENTATION("CensusPlus 2016 Technical Documentation",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2016_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2016_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_2014_VARIABLES("CensusPlus 2014 Variables",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2014.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2014.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_2014_RELEASE_NOTES("CensusPlus 2014 Release Notes",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2014_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2014_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_FAQS("CensusPlus FAQs",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFAQs.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFAQs.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_2011_RELEASE_NOTES("CensusPlus 2011 Release Notes",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2011_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus_2011_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),
    CENSUSPLUS_2011_TECHNICAL_DOCUMENT("CensusPlus 2011 Technical Document",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus2011_-_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCensusPlus2011_-_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "Census Plus"),

    //ENVIRONICS - DEMO_STATS
    DEMOSTATS_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    DEMOSTATS_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    DEMOSTATS_TECHNICAL_DOCUMENT_2019("Technical Document 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2019_-_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2019_-_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    DEMOSTATS_TECHNICAL_DOCUMENT_2020("Technical Document 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2020_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2020_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    DEMOSTATS_VARIABLE_LIST_2019("Variable List 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    DEMOSTATS_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),

    //ENVIRONICS - DEMO_STATS TRENDS
    DEMOSTATUS_TRENDS_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_Trends_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https:/test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_Trends_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    DEMOSTATUS_TRENDS_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_Trends_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDemoStats_Trends_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),

    //ENVIRONICS - HOUSEHOLD_SPEND
    HOUSEHOLD_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    HOUSEHOLD_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    HOUSEHOLD_TECHNICAL_DOCUMENT_2019("Technical Document 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2019_-_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2019_-_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    HOUSEHOLD_TECHNICAL_DOCUMENT_2020("Technical Document 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2020_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2020_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    HOUSEHOLD_VARIABLE_LIST_2019("Variable List 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    HOUSEHOLD_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),
    HOUSEHOLD_SURVEY_OF_HOUSEHOLD_SPENDING("Survey of Household Spending",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2019_Survey_of_Household_Spending_Questions_Canada.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2019_Survey_of_Household_Spending_Questions_Canada.pdf%22%7D&f=application%2Fpdf",
            "Demo Stat and Haushold Spend"),

    //ENVIRONICS - DAYTIME_POP
    DAYTIMEPOP_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    DAYTIMEPOP_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    DAYTIMEPOP_VARIABLE_LIST_2019("Variable List 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    DAYTIMEPOP_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FDaytimePop_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - FOOD_SPEND
    FOODSPEND_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    FOODSPEND_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    FOODSPEND_TECHNICAL_DOCUMENT_2019("Technical Document 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2019_-_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2019_-_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    FOODSPEND_TECHNICAL_DOCUMENT_2020("Technical Document 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2020_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FHouseholdSpend_and_FoodSpend_2020_Technical_Documentation.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    FOODSPEND_VARIABLE_LIST_2019("Variable List 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    FOODSPEND_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FFoodSpend_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - AGE BY INCOME
    AGE_BY_INCOME_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    AGE_BY_INCOME_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    AGE_BY_INCOME_VARIABLE_LIST_2019("Variable List 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    AGE_BY_INCOME_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FAgeByIncome_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - COMMUNITY_HEALTH
    COMMUNITY_HEALTH_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    COMMUNITY_HEALTH_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    COMMUNITY_HEALTH_VARIABLE_LIST_2019("Variable List 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2019_-_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    COMMUNITY_HEALTH_VARIABLE_LIST_2020("Variable List 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FCommunityHealth_2020_Variables_List.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - DIGITAL LIFESTYLE DATASET - OPTICKS SOCIAL
    OPTICKS_SOCIAL_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Social_Powered_by_AskingCanadians_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Social_Powered_by_AskingCanadians_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    OPTICKS_SOCIAL_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Social_Powered_by_AskingCanadians_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Social_Powered_by_AskingCanadians_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - DIGITAL LIFESTYLE DATASET - OPTICKS MOBILE
    OPTICKS_MOBILE_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Mobile_Powered_by_AskingCanadians_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Mobile_Powered_by_AskingCanadians_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    OPTICKS_MOBILE_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Mobile_Powered_by_AskingCanadians_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_Mobile_Powered_by_AskingCanadians_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - DIGITAL LIFESTYLE DATASET - OPTICKS ESHOPPER
    OPTICKS_ESHOPPER_RELEASE_NOTES_2019("Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_eShopper_Powered_by_AskingCanadians_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_eShopper_Powered_by_AskingCanadians_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),
    OPTICKS_ESHOPPER_RELEASE_NOTES_2020("Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_eShopper_Powered_by_AskingCanadians_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FOpticks_eShopper_Powered_by_AskingCanadians_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Environics"),

    //ENVIRONICS - PRIZM
    PRIZM_SNAPSHOTS_2021("PRIZM Snapshots 2021",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2021_PRIZMCA_Snapshots.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2021_PRIZMCA_Snapshots.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_SNAPSHOTS_2020("PRIZM Snapshots 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FSA_PRIZM_Segment_Snapshots_2020.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FSA_PRIZM_Segment_Snapshots_2020.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_SNAPSHOTS_2019("PRIZM5 Snapshots 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_Snapshots_2019.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_Snapshots_2019.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_SOCIAL_GROUPS_AND_LIFESTAGES("PRIZM Social Groups and LifeStages",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM2020CA_SESI_SG_LG-1.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM2020CA_SESI_SG_LG-1.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_MARKETERS_HANDBOOK_2015("PRIZM Marketer’s Handbook 2015",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2015.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2015.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_MARKETERS_HANDBOOK_2016("PRIZM Marketer’s Handbook 2016",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2016.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2016.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_MARKETERS_HANDBOOK_2018("PRIZM Marketer’s Handbook 2018",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2018.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2018.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_MARKETERS_HANDBOOK_2019("PRIZM Marketer’s Handbook 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2019_PRIZM_Handbook_PRINT_Updated.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2019_PRIZM_Handbook_PRINT_Updated.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_MARKETERS_HANDBOOK_2020("PRIZM Marketer’s Handbook 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_Marketers_Guide.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_Marketers_Guide.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_MARKETERS_HANDBOOK_2021("PRIZM Marketer’s Handbook 2021",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FEA_PRIZM_Guide_2021.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FEA_PRIZM_Guide_2021.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_FRENCH_HANDBOOK_2015("PRIZM French Handbook 2015",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2015_FRENCH.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2015_FRENCH.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_FRENCH_HANDBOOK_2016("PRIZM French Handbook 2016",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2016_FRENCH.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2016_FRENCH.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_FRENCH_HANDBOOK_2018("PRIZM French Handbook 2018",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2018_FRENCH.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_Handbook_2018_FRENCH.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_FRENCH_HANDBOOK_2019("PRIZM French Handbook 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2019_PRIZM_Handbook_French.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2F2019_PRIZM_Handbook_French.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_FRENCH_HANDBOOK_2020("PRIZM French Handbook 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_French_Marketers_Guide.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_French_Marketers_Guide.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_RELEASE_NOTES_2018("PRIZM Release Notes 2018",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_2018_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM5_2018_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_RELEASE_NOTES_2019("PRIZM Release Notes 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2019_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM5_RELEASE_NOTES_2020("PRIZM Release Notes 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_TECHNICAL_DOCUMENT_2019("PRIZM Technical Document 2019",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2019_-_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2019_-_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),
    PRIZM_TECHNICAL_DOCUMENT_2020("PRIZM Technical Document 2020",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FPRIZM_2020_Technical_Document.pdf%22%7D&f=application%2Fpdf",
            "Prizm"),

    //AMERICAN COMMUNITY SURVEY (ACS)
    ACS_2018_SUBJECT_DEFINITIONS("ACS 2018 Subject Definitions",
            "https://assets.simplyanalytics.com/documents/2018-ACS-Subject-Definitions.pdf",
            "https://assets.simplyanalytics.com/documents/2018-ACS-Subject-Definitions.pdf",
            "Acs"),
    ACS_2018_GROUP_QUARTERS_DEFINITIONS("ACS 2018 Group Quarters Definitions",
            "https://assets.simplyanalytics.com/documents/2018_ACS_GQ_Definitions.pdf",
            "https://assets.simplyanalytics.com/documents/2018_ACS_GQ_Definitions.pdf",
            "Acs"),

    //APPLIED GEOGRAPHICAL SOLUTIONS, INC. (AGS)
    ASSETS_AND_DEBTS_METHODOLOGY("Assets and Debts Methodology",
            "https://assets.simplyanalytics.com/documents/AGS-Assets-and-Debts-Methodology-2018B.pdf",
            "https://assets.simplyanalytics.com/documents/AGS-Assets-and-Debts-Methodology-2018B.pdf",
            "Ags"),
    ESTIMATE_AND_PROJECTTIONS_METHODOLOGY("Estimates & Projections Methodology",
            "https://assets.simplyanalytics.com/documents/AGS-Estimates-and-Projections-Methodology-2019A.pdf",
            "https://assets.simplyanalytics.com/documents/AGS-Estimates-and-Projections-Methodology-2019A.pdf",
            "Ags"),

    //GFK MRI
 /* GFK_VARIABLE_LIST_2018("Variable List 2018",
          "https://assets.simplyanalytics.com/documents/EASI_MRI_26_Propensity_Reports_2018.pdf",
          "https://assets.simplyanalytics.com/documents/EASI_MRI_26_Propensity_Reports_2018.pdf",
          "Gfk"), this data is no longer available */

    //DUN & BRADSTREET
    D_AND_B_GLOBAL_DATA_COLLECTION_AND_WORLDBASE("D&B Global Data Collection & WorldBase",
            "https://assets.simplyanalytics.com/documents/Dun_and_Bradstreet_Global_Data_Collection_WorldBase.pdf",
            "https://assets.simplyanalytics.com/documents/Dun_and_Bradstreet_Global_Data_Collection_WorldBase.pdf",
            "Dandb"),
    D_AND_B_SALES_VOLUME_FACCT_SHEET("Sales Volume Fact Sheet",
            "https://assets.simplyanalytics.com/documents/2020-03_Sales_Volume_New_FACT_FAQ.pdf",
            "https://assets.simplyanalytics.com/documents/2020-03_Sales_Volume_New_FACT_FAQ.pdf",
            "Dandb"),

    //CLARITAS
    CLARITAS_HOMEPAGE("www.claritas.com",
            "http://www.claritas.com",
            "http://www.claritas.com",
            "Claritas"),

    //CLARITAS - PRIZM
    PRIZM_SEGMENT_NARRATIVES("PRIZM™ Segment Narratives",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Segment_Narratives_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Segment_Narratives_2016.pdf",
            "Claritas"),
    PRIZM_METHODOLOGY("PRIZM™ Methodology",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Methodology.pdf",
            "Claritas"),
    PRIZM_CYFY_DISTIBUTION_RELEASE_NOTES_2016("PRIZM™ CY/FY Distributions Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZMCY_FY_Distributions_Release_Notes_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZMCY_FY_Distributions_Release_Notes_2016.pdf",
            "Claritas"),
    PRIZM_CYFY_DISTIBUTION_RELEASE_NOTES_2017("PRIZM™ CY/FY Distributions Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_CY_FY_Distributions_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_CY_FY_Distributions_Release_Notes_2017.pdf",
            "Claritas"),

    //CLARITAS - PRIZM PREMIER
    PRIZM_PREMIER_SEGMENT_NARRATIVES_2016("PRIZM® Premier Segment Narratives 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Premier_Segment_Narratives_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Premier_Segment_Narratives_2016.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_SEGMENT_NARRATIVES_2018("PRIZM® Premier Segment Narratives 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Narratives_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Narratives_2018.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_SEGMENT_NARRATIVES_2019("PRIZM® Premier Segment Narratives 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Narratives_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Narratives_2019.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_SEGMENT_NARRATIVES_2020("PRIZM® Premier Segment Narratives 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Narratives_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Narratives_2020.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_2016_METHODOLOGY("PRIZM® Premier 2016 Methodology",
            "https://assets.simplyanalytics.com/documents/PRIZM_Premier_Methodology_2015.pdf",
            "https://assets.simplyanalytics.com/documents/PRIZM_Premier_Methodology_2015.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_2018_METHODOLOGY("PRIZM® Premier 2018 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_2018_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_2018_Methodology.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_2019_METHODOLOGY("PRIZM® Premier 2019 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Methodology_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Methodology_2019.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_2020_METHODOLOGY("PRIZM® Premier 2020 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Methodology_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Methodology_2020.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_2021_METHODOLOGY("PRIZM® Premier 2021 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Methodology_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Methodology_2021.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_SEGMENT_NARRATIVES_2021("PRIZM® Premier Segment Narratives 2021",
            "https://assets.simplyanalytics.com/documents/PRIZM_Premier_Segment_Narratives_2021.pdf",
            "https://assets.simplyanalytics.com/documents/PRIZM_Premier_Segment_Narratives_2021.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_LIFESTAGE_STORYBOARDS_2019("PRIZM® Premier Lifestage Storyboards 2019",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Premier_Storyboards.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Premier_Storyboards.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_LIFESTAGE_STORYBOARDS_2020("PRIZM® Premier Lifestage Storyboards 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Lifestage_Group_Storyboards_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Lifestage_Group_Storyboards_2020.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_LIFESTAGE_STORYBOARDS_2021("PRIZM® Premier Lifestage Storyboards 2021",
            "https://assets.simplyanalytics.com/documents/2021_PRIZM_Premier_Lifestage_Storyboards.pptx",
            "https://assets.simplyanalytics.com/documents/2021_PRIZM_Premier_Lifestage_Storyboards.pptx",
            "Claritas Prizm"),
    PRIZM_PREMIER_SEGMENT_STORYBOARD_2020("PRIZM® Premier Segment Storyboards 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Storyboards_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Storyboards_2020.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_SEGMENT_STORYBOARD_2021("PRIZM® Premier Segment Storyboards 2021",
            "https://assets.simplyanalytics.com/documents/2021_PRIZM_Premier_Segment_Storyboards.pptx",
            "https://assets.simplyanalytics.com/documents/2021_PRIZM_Premier_Segment_Storyboards.pptx",
            "Claritas Prizm"),
    PRIZM_PREMIER_CYFY_DISTIBUTION_RELEASE_NOTES_2016("PRIZM® Premier CY/FY Distributions Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/PRIZM_Premier_2016_CY_FY_Distributions_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/PRIZM_Premier_2016_CY_FY_Distributions_Release_Notes.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_CYFY_DISTIBUTION_RELEASE_NOTES_2017("PRIZM® Premier CY/FY Distributions Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Premier_CY_FY_Distributions_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_PRIZM_Premier_CY_FY_Distributions_Release_Notes_2017.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_CYFY_DISTIBUTION_RELEASE_NOTES_2018("PRIZM® Premier Segment Descriptors Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Descriptors_Release_Notes_2018_final.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Descriptors_Release_Notes_2018_final.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIERE_RELEASE_NOTES_2019("PRIZM® Premier Release Notes 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_ZIP_6_Distributions_Release_Notes_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_ZIP_6_Distributions_Release_Notes_2019.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_CY_FY_DISTRIBUTION_RELEASE_NOTES_2020("PRIZM® Premier CY/FY Distributions Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_CY_FY_Distributions_Release_Notes_2020_.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_CY_FY_Distributions_Release_Notes_2020_.pdf",
            "Claritas Prizm"),
    PRIZM_PREMIER_CY_FY_DISTRIBUTION_RELEASE_NOTES_2021("PRIZM® Premier CY/FY Distributions Release Notes 2021",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Descriptors_Release_Notes_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PRIZM_Premier_Segment_Descriptors_Release_Notes_2021.pdf",
            "Claritas Prizm"),

    //CLARITAS CONSUMER BUYING POWER
    CONSUMER_BUYING_POWER_AND_RETAIL_MARKET_POWER_OVERVIEW("Consumer Buying Power and Retail Market Power® Overview",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_and_Retail_Market_Power.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_and_Retail_Market_Power.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_SUMMARY_METHODOLOGY("Consumer Buying Power® Summary Methodology",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_Summary_Methodology_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_Summary_Methodology_2016.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2016("Consumer Buying Power® Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_Release_Notes_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_Release_Notes_2016.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2017("Consumer Buying Power® Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Consumer_Buying_Power_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Consumer_Buying_Power_Release_Notes_2017.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2018("Consumer Buying Power® Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Consumer_Buying_Power_2018_-_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Consumer_Buying_Power_2018_-_Release_Notes.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2019("Consumer Buying Power® Release Notes 2019",
            "https://assets.simplyanalytics.com/documents/Consumer_Buying_Power_2019_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Consumer_Buying_Power_2019_Release_Notes.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2020("Consumer Buying Power® Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Environics_Analytics_Consumer_Buying_Power_2020_-_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Environics_Analytics_Consumer_Buying_Power_2020_-_Release_Notes.pdf",
            "Claritas Consumer Buying Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2021("Consumer Buying Power® Release Notes 2021",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FEnvironics_Analytics_Consumer_Buying_Power_2021_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FEnvironics_Analytics_Consumer_Buying_Power_2021_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Claritas Consumer Buying Power"),

    //CLARITAS RETAIL MARKET POWER
    CONSUMER_BUYING_POWER_AND_RETAIL_MARKET_POWER_OVERVIEW_MARKET("Consumer Buying Power and Retail Market Power® Overview",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_and_Retail_Market_Power.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Consumer_Buying_Power_and_Retail_Market_Power.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_SUMMARY_METHODOLOGY_MARKET("Retail Market Power® Methodology",
            "https://assets.simplyanalytics.com/documents/Nielsen_Retail_Market_Power_Methodology_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Retail_Market_Power_Methodology_2016.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2016_MARKET("Retail Market Power® Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_Retail_Market_Power_Release_Notes_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Retail_Market_Power_Release_Notes_2016.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2017_MARKET("Retail Market Power® Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_Release_Notes_2017.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2018_MARKET("Retail Market Power® Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_2018_Release_Notes_Flat_Files.pdf",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_2018_Release_Notes_Flat_Files.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2019_MARKET("Retail Market Power® Release Notes 2019",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_2019_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_2019_Release_Notes.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2020_MARKET("Retail Market Power® Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_2020_-_Release_Notes_Flat_File.pdf",
            "https://assets.simplyanalytics.com/documents/Retail_Market_Power_2020_-_Release_Notes_Flat_File.pdf",
            "Claritas Retail Market Power"),
    CONSUMER_BUYING_POWER_RELEASE_NOTES_2021_MARKET("Retail Market Power® Release Notes 2021",
            "/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FEnvironics_Analytics_Retail_Market_Power_2021_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "https://test.simplyanalytics.net/dispatch.php?v=get&r=asset&d=%7B%22key%22%3A%22documents%2FEnvironics_Analytics_Retail_Market_Power_2021_-_Release_Notes.pdf%22%7D&f=application%2Fpdf",
            "Claritas Retail Market Power"),

    //CLARITAS FINANCIAL CLOUT
    FINANCIAL_CLOUT_RELEASE_NOTES_2016("Financial CLOUT® Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_Financial_CLOUT_Release_Notes_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Financial_CLOUT_Release_Notes_2016.pdf",
            "Financial CLOUT"),
    FINANCIAL_CLOUT_RELEASE_NOTES_2017("Financial CLOUT® Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Nielsen_Financial_CLOUT_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_Financial_CLOUT_Release_Notes_2017.pdf",
            "Financial CLOUT"),
    FINANCIAL_CLOUT_RELEASE_NOTES_2018("Financial CLOUT® Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_Release_Notes_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_Release_Notes_2018.pdf",
            "Financial CLOUT"),
    FINANCIAL_CLOUT_RELEASE_NOTES_2019("Financial CLOUT® Release Notes 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2019_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2019_Release_Notes.pdf",
            "Financial CLOUT"),
    FINANCIAL_CLOUT_RELEASE_NOTES_2020("Financial CLOUT® Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2020_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2020_Release_Notes.pdf",
            "Financial CLOUT"),
    FINANCIAL_CLOUT_RELEASE_NOTES_2021("Financial CLOUT® Release Notes 2021",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2021_Release_Notes.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2021_Release_Notes.pdf",
            "Financial CLOUT"),
    FINANCIAL_CLOUT_METHODOLOGY("Financial CLOUT® Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2022_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_CLOUT_2022_Methodology.pdf",
            "Financial CLOUT"),
    FINANCIAL_TRACK_REDESIGN_2019_AND_CLOUT_UPDATE_2021("Claritas Financial Track Redesign 2019 and Financial CLOUT® Update 2021",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_Track_Redesign_2019_and_Financial_CLOUT_2021_Update.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_Financial_Track_Redesign_2019_and_Financial_CLOUT_2021_Update.pdf",
            "Financial CLOUT"),

    //CLARITAS CONNEXTIONS
    CONNEXIONS_SEGMENT_NARRATIVES_2016("ConneXions Segment Narratives 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_ConneXions_Segment_Narratives_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_ConneXions_Segment_Narratives_2016.pdf",
            "Connexions"),
    CONNEXIONS_SEGMENT_NARRATIVES_2018("ConneXions Segment Narratives 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Narratives_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Narratives_2018.pdf",
            "Connexions"),
    CONNEXIONS_SEGMENT_NARRATIVES_2019("ConneXions Segment Narratives 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Narratives_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Narratives_2019.pdf",
            "Connexions"),
    CONNEXIONS_SEGMENT_NARRATIVES_2020("ConneXions Segment Narratives 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Narratives_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Narratives_2020.pdf",
            "Connexions"),
    CONNEXIONS_SEGMENT_NARRATIVES_2021("ConneXions Segment Narratives 2021",
            "https://assets.simplyanalytics.com/documents/ConneXions_Segment_Narratives_2021.pdf",
            "https://assets.simplyanalytics.com/documents/ConneXions_Segment_Narratives_2021.pdf",
            "Connexions"),
    CONNEXIONS_CYFY_DISTIBUTION_RELEASE_NOTES_2016("ConneXions CY/FY Distributions Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_ConneXions_CY_FY_Distributions_Release_Notes_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_ConneXions_CY_FY_Distributions_Release_Notes_2016.pdf",
            "Connexions"),
    CONNEXIONS_CYFY_DISTIBUTION_RELEASE_NOTES_2017("ConneXions CY/FY Distributions Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Nielsen_ConneXions_CY_FY_Distributions_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_ConneXions_CY_FY_Distributions_Release_Notes_2017.pdf",
            "Connexions"),
    CONNEXIONS_CYFY_DISTIBUTION_RELEASE_NOTES_2018("ConneXions CY/FY Distributions Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_CYFY_Distributions_Release_Notes_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_CYFY_Distributions_Release_Notes_2018.pdf",
            "Connexions"),
    CONNEXIONS_CYFY_DISTIBUTION_RELEASE_NOTES_2019("ConneXions CY/FY Distributions Release Notes 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_CY_FY_Household_Distributions_Release_Notes_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_CY_FY_Household_Distributions_Release_Notes_2019.pdf",
            "Connexions"),
    CONNEXIONS_CYFY_DISTIBUTION_RELEASE_NOTES_2020("ConneXions CY/FY Distributions Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_CY_FY_Household_Distributions_Release_Notes_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_CY_FY_Household_Distributions_Release_Notes_2020.pdf",
            "Connexions"),
    CONNEXIONS_CYFY_DISTIBUTION_RELEASE_NOTES_2021("ConneXions CY/FY Distributions Release Notes 2021",
            "https://assets.simplyanalytics.com/documents/claritas-connexions-cy-distributions-release-notes.pdf",
            "https://assets.simplyanalytics.com/documents/claritas-connexions-cy-distributions-release-notes.pdf",
            "Connexions"),
    CONNEXIONS_METHODOLOGY_2021("ConneXions Methodology 2021 ",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Methodology_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Methodology_2021.pdf",
            "Connexions"),
    CONNEXIONS_LIFESTAGE_GROUPS("ConneXions Lifestage Groups",
            "https://assets.simplyanalytics.com/documents/2021_ConneXions_Lifestage_Group_Storyboards.pptx",
            "https://assets.simplyanalytics.com/documents/2021_ConneXions_Lifestage_Group_Storyboards.pptx",
            "Connexions"),
    PSYLE_AND_CONNEXIONS_SEGMENT_DESCRIPTORS_RELEASE_NOTES_2018_1("P$YCLE and ConneXions Segment Descriptors Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_and_ConneXions_Segment_Descriptors_Release_Notes_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_and_ConneXions_Segment_Descriptors_Release_Notes_2018.pdf",
            "Connexions"),
    PSYLE_AND_CONNEXIONS_SEGMENT_DESCRIPTORS_RELEASE_NOTES_2020_1("P$YCLE and ConneXions Segment Descriptors Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/claritas-connexions-segment-descriptors-release-notes-ea.pdf",
            "https://assets.simplyanalytics.com/documents/claritas-connexions-segment-descriptors-release-notes-ea.pdf",
            "Connexions"),
    PSYLE_AND_CONNEXIONS_SEGMENT_DESCRIPTORS_RELEASE_NOTES_2021_1("P$YCLE and ConneXions Segment Descriptors Release Notes 2021",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Descriptors_Release_Notes_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Descriptors_Release_Notes_2021.pdf",
            "Connexions"),
    CONNEXIONS_SEGMENT_STORYBOARDS_2021("ConneXions Segment Storyboards 2021",
            "https://assets.simplyanalytics.com/documents/2021_ConneXions_Segment_Storyboards.pptx",
            "https://assets.simplyanalytics.com/documents/2021_ConneXions_Segment_Storyboards.pptx",
            "Connexions"),

    //CLARITAS PSYCLE
    PSYCLE_SEGMENT_NARRATIVES_2016("P$YCLE Segment Narratives 2016",
            "https://assets.simplyanalytics.com/documents/Nielsen_P%24YCLE_Segment_Narratives_2016.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_P%24YCLE_Segment_Narratives_2016.pdf",
            "Psycle"),
    PSYCLE_SEGMENT_NARRATIVES_2018("P$YCLE Segment Narratives 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Segment_Narratives_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Segment_Narratives_2018.pdf",
            "Psycle"),
    PSYCLE_SEGMENT_NARRATIVES_2019("P$YCLE Segment Narratives 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Segment_Narratives_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Segment_Narratives_2019.pdf",
            "Psycle"),
    PSYCLE_SEGMENT_NARRATIVES_2020("P$YCLE Segment Narratives 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_P%24YCLE_Segment_Narratives_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_P%24YCLE_Segment_Narratives_2020.pdf",
            "Psycle"),
    PSYCLE_CYFY_DISTIBUTION_RELEASE_NOTES_2016("P$YCLE CY/FY Distributions Release Notes 2016",
            "https://assets.simplyanalytics.com/documents/P%24YCLE_CY_FY_Distributions_Release_Notes_2016.pdf",
            "https://assets.simplyanalytics.com/documents/P%24YCLE_CY_FY_Distributions_Release_Notes_2016.pdf",
            "Psycle"),
    PSYCLE_CYFY_DISTIBUTION_RELEASE_NOTES_2017("P$YCLE CY/FY Distributions Release Notes 2017",
            "https://assets.simplyanalytics.com/documents/Nielsen_P%24YCLE_CY_FY_Distributions_Release_Notes_2017.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_P%24YCLE_CY_FY_Distributions_Release_Notes_2017.pdf",
            "Psycle"),
    PSYCLE_CYFY_DISTIBUTION_RELEASE_NOTES_2018("P$YCLE CY/FY Distributions Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_CY_FY_Distributions_Release_Notes_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_CY_FY_Distributions_Release_Notes_2018.pdf",
            "Psycle"),
    PSYCLE_CYFY_DISTIBUTION_RELEASE_NOTES_2019("P$YCLE CY/FY Distributions Release Notes 2019",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_CY_FY_Distributions_Release_Notes_2019.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_CY_FY_Distributions_Release_Notes_2019.pdf",
            "Psycle"),
    PSYCLE_CYFY_DISTIBUTION_RELEASE_NOTES_2020("P$YCLE CY/FY Distributions Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_P$YCLE_CY_FY_Distributions_Release_Notes_2020_.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_P$YCLE_CY_FY_Distributions_Release_Notes_2020_.pdf",
            "Psycle"),
    PSYCLE_LIFESTAGE_GROUPS("P$YCLE Lifestage Groups",
            "https://assets.simplyanalytics.com/documents/Nielsen_P%24YCLE_Lifestage_Groups.pdf",
            "https://assets.simplyanalytics.com/documents/Nielsen_P%24YCLE_Lifestage_Groups.pdf",
            "Psycle"),
    PSYCLE_2018_METHODOLOGY("P$YCLE 2018 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_2018_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_2018_Methodology.pdf",
            "Psycle"),
    PSYLE_AND_CONNEXIONS_SEGMENT_DESCRIPTORS_RELEASE_NOTES_2018_2("P$YCLE and ConneXions Segment Descriptors Release Notes 2018",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_and_ConneXions_Segment_Descriptors_Release_Notes_2018.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_and_ConneXions_Segment_Descriptors_Release_Notes_2018.pdf",
            "Psycle"),
    PSYLE_AND_CONNEXIONS_SEGMENT_DESCRIPTORS_RELEASE_NOTES_2020_2("P$YCLE and ConneXions Segment Descriptors Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/claritas-connexions-segment-descriptors-release-notes-ea.pdf",
            "https://assets.simplyanalytics.com/documents/claritas-connexions-segment-descriptors-release-notes-ea.pdf",
            "Psycle"),
    PSYLE_AND_CONNEXIONS_SEGMENT_DESCRIPTORS_RELEASE_NOTES_2021_2("P$YCLE and ConneXions Segment Descriptors Release Notes 2021",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Descriptors_Release_Notes_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_ConneXions_Segment_Descriptors_Release_Notes_2021.pdf",
            "Psycle"),

    //CLARITAS PSYCLE PREMIER
    PSYCLE_PREMIER_2020_METHODOLOGY("P$YCLE Premier 2020 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_2020_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_2020_Methodology.pdf",
            "Psycle"),
    PSYCLE_PREMIER_2021_METHODOLOGY("P$YCLE Premier 2021 Methodology",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Methodology_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Methodology_2021.pdf",
            "Psycle"),
    PSYCLE_PREMIER_LIFESTAGE_STORYBOARD_2021("P$YCLE Premier Lifestage Storyboards 2021",
            "https://assets.simplyanalytics.com/documents/2021_PSYCLE_Premier_Lifestage_Group_Storyboards.pptx",
            "https://assets.simplyanalytics.com/documents/2021_PSYCLE_Premier_Lifestage_Group_Storyboards.pptx",
            "Psycle"),
    PSYCLE_PREMIER_CY_FY_DISTRIBUTION_RELEASE_NOTES_2020("P$YCLE Premier CY/FY Distributions Release Notes 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_CY_FY_Distributions_Release_Notes_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_CY_FY_Distributions_Release_Notes_2020.pdf",
            "Psycle"),
    PSYCLE_PREMIER_CY_FY_DISTRIBUTION_RELEASE_NOTES_2021("P$YCLE Premier CY/FY Distributions Release Notes 2021",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Segment_Descriptors_Release_Notes_2021.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Segment_Descriptors_Release_Notes_2021.pdf",
            "Psycle"),
    PSYCLE_PREMIER_SEGMENT_NARRATIVES_2020("P$YCLE Premier Segment Narratives 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Segment_Narratives_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Segment_Narratives_2020.pdf",
            "Psycle"),
    PSYCLE_PREMIER_SEGMENT_NARRATIVES_2021("P$YCLE Premier Segment Narratives 2021",
            "https://assets.simplyanalytics.com/documents/PSYCLE_Premier_Segment_Narratives_2021.pdf",
            "https://assets.simplyanalytics.com/documents/PSYCLE_Premier_Segment_Narratives_2021.pdf",
            "Psycle"),
    PSYCLE_PREMIER_SEGMENT_STORYBOARD_2020("P$YCLE Premier Segment Storyboards 2020",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Segment_Storyboards_2020.pdf",
            "https://assets.simplyanalytics.com/documents/Claritas_PSYCLE_Premier_Segment_Storyboards_2020.pdf",
            "Psycle"),
    PSYCLE_PREMIER_SEGMENT_STORYBOARD_2021("P$YCLE Premier Segment Storyboards 2021",
            "https://assets.simplyanalytics.com/documents/2021_PSYCLE_Premier_Segment_Storyboards.pptx",
            "https://assets.simplyanalytics.com/documents/2021_PSYCLE_Premier_Segment_Storyboards.pptx",
            "Psycle"),

    //NIELSON
    NIELSEN_SCARBOROUGH_MARKETS_2017("Nielsen Scarborough Markets 2017 (SA 2018 Survey)",
            "https://assets.simplyanalytics.com/documents/2018-11-21_Nielsen_Scarborough_Markets_2017.pdf",
            "https://assets.simplyanalytics.com/documents/2018-11-21_Nielsen_Scarborough_Markets_2017.pdf",
            "Nielsen"),
    NIELSEN_SCARBOROUGH_MARKETS_2016("Nielsen Scarborough Markets 2016 (SA 2017 Survey)",
            "https://assets.simplyanalytics.com/documents/2018-11-21_Nielsen_Scarborough_Markets_2016.pdf",
            "https://assets.simplyanalytics.com/documents/2018-11-21_Nielsen_Scarborough_Markets_2016.pdf",
            "Nielsen"),
    NIELSEN_SCARBOROUGH_MID_TIER_METHODOLOGY_2016("Nielsen Scarborough Mid-Tier Methodology 2016 (SA 2017 Survey)",
            "https://assets.simplyanalytics.com/documents/2018-11-14_Nielsen_Scarborough_Mid-Tier_Methodology_2015.pdf",
            "https://assets.simplyanalytics.com/documents/2018-11-14_Nielsen_Scarborough_Mid-Tier_Methodology_2015.pdf",
            "Nielsen"),
    NIELSEN_SCARBOROUGH_METHODOLOGY_TOP_TIER_PPHONE_2016("Nielsen Scarborough Methodology Top Tier Phone 2016 (SA 2017 Survey)",
            "https://assets.simplyanalytics.com/documents/2018-11-14_Nielsen_Scarborough_Methodology_Top_Tier_Phone_2015.pdf",
            "https://assets.simplyanalytics.com/documents/2018-11-14_Nielsen_Scarborough_Methodology_Top_Tier_Phone_2015.pdf",
            "Nielsen"),
    NIELSEN_SCARBOROUGH_METHODOLOGY_TOP_TIER_ADDRESS_BASED_2016("Nielsen Scarborough Methodology Top Tier Address Based 2016 (SA 2017 Survey)",
            "https://assets.simplyanalytics.com/documents/2018-11-14_Nielsen_Scarborough_Methodology_Top_Tier_Address_Based_2015.pdf",
            "https://assets.simplyanalytics.com/documents/2018-11-14_Nielsen_Scarborough_Methodology_Top_Tier_Address_Based_2015.pdf",
            "Nielsen"),

    //SIMMONS RESEARCH
    //SIMMONS NCS
    NCS_DESCRIPTION_OF_METHODOLOGY_FALL_2018("NCS Description of Methodology Fall 2018 (SA 2019 Survey)",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Fall_2018_12-Month_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Fall_2018_12-Month_Methodology.pdf",
            "NCS"),
    NCS_DESCRIPTION_OF_METHODOLOGY_FALL_2017("NCS Description of Methodology Fall 2017 (SA 2018 Survey)",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FFA17_NHCS_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FFA17_NHCS_Methodology.pdf",
            "NCS"),
    NCS_CODING_PRODUCT_USAGE("NCS Coding Product Usage",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Coding-Product_Usage_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Coding-Product_Usage_FA18.pdf",
            "NCS"),
    NCS_SPECIAL_CLEANING_RULES("NCS Special Cleaning Rules",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Special_Cleaning_Rules_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Special_Cleaning_Rules_FA18.pdf",
            "NCS"),
    NCS_PRODUCT_TYPES("NCS Product Types",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Product_Types_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Product_Types_FA18.pdf",
            "NCS"),
    NCS_GEOGRAPHIC_DEFINITIONS("NCS Geographic Definitions",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Geographic_Definitions_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Geographic_Definitions_FA18.pdf",
            "NCS"),
    NCS_PSYCHOGRAPHIC_SCALES("NCS Psychographic Scales",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Psychographic_Scale_Definitions_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Psychographic_Scale_Definitions_FA18.pdf",
            "NCS"),
    NCS_HISPANIC_CULTURAL_IDENTIFICATION_SCALES("NCS Hispanic Cultural Identification Scales",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Hispanic_Cultural_Identification_Scales_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Hispanic_Cultural_Identification_Scales_FA18.pdf",
            "NCS"),
    NCS_QUANTILE_TERCILE_MEDIA_USAGE_GROUPS("NCS Quantile, Tercile Media Usage Groups",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Quintile_Tercile_Media_Usage_Groups_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Quintile_Tercile_Media_Usage_Groups_FA18.pdf",
            "NCS"),
    NCS_RADIO_FORMATS("NCS Radio Formats",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Radio_Formats_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Radio_Formats_FA18.pdf",
            "NCS"),
    NCS_INDUSTRY_OCCUPATION_DEFINITION("NCS Industry Occupation Definitions",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Industry-Occupation_Definitions_FA18.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_NCS%2FNCS_Industry-Occupation_Definitions_FA18.pdf",
            "NCS"),

    //SIMMONS LOCAL CONSUMER INSIGHTS
    SIMONS_LOCAL_VARIABLE_LIST("SimmonsLOCAL Variable List",
            "https://assets.simplyanalytics.com/documents/Experian_SimmonsLocal_Content_HighLevel.pdf",
            "https://assets.simplyanalytics.com/documents/Experian_SimmonsLocal_Content_HighLevel.pdf",
            "Simons"),
    SIMONS_LOCAL_METHODOLOGY("SimmonsLOCAL Methodology",
            "https://assets.simplyanalytics.com/documents/SimmonsLOCAL_Methodology.pdf",
            "https://assets.simplyanalytics.com/documents/SimmonsLOCAL_Methodology.pdf",
            "Simons"),
    SIMONS_LOCAL_METHODOLOGY_II("SimmonsLOCAL Methodology II",
            "https://assets.simplyanalytics.com/documents/SimmonsLOCAL_Methodology_Overview-2.pdf",
            "https://assets.simplyanalytics.com/documents/SimmonsLOCAL_Methodology_Overview-2.pdf",
            "Simons"),
    SIMONS_LOCAL_PRODUCT_RELEASE_NOTES_2014("SimmonsLOCAL Product Release Notes 2014",
            "https://assets.simplyanalytics.com/documents/SimmonsLOCAL_Product_Release_Notes_2014.pdf",
            "https://assets.simplyanalytics.com/documents/SimmonsLOCAL_Product_Release_Notes_2014.pdf",
            "Simons"),
    SIMONS_DEFINITIONS("Simmons Definitions",
            "https://assets.simplyanalytics.com/documents/Simmons_National_Consumer_Study_Definitions.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_National_Consumer_Study_Definitions.pdf",
            "Simons"),
    SIMONS_CONSUMER_SEGMENT_DEFINITIONS("Simmons Consumer Segment Definitions",
            "https://assets.simplyanalytics.com/documents/Simmons_Consumer_Segment_Definitions.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_Consumer_Segment_Definitions.pdf",
            "Simons"),
    COVID_19_CONSUMER_INSIGHT_STUDY("COVID-19 Consumer Insights Study",
            "https://assets.simplyanalytics.com/documents/Simmons_COVID-19_Consumer_Insights_Study.pdf",
            "https://assets.simplyanalytics.com/documents/Simmons_COVID-19_Consumer_Insights_Study.pdf",
            "Simons"),

    //SIMMONS MOSAIC USA
    SIMONS_MOSAIC_HANDBOOK("Simmons Mosaic® USA Descriptions",
            "https://assets.simplyanalytics.com/documents/2021_Mosaic_USA_Handbook.pdf",
            "https://assets.simplyanalytics.com/documents/2021_Mosaic_USA_Handbook.pdf",
            "Simons"),

    /*SIMONS_MOSAIC_DESCRIPTIONS("Simmons Mosaic® USA Descriptions",
            "https://assets.simplyanalytics.com/documents/Mosaic_USA_Descriptions.pdf",
            "https://assets.simplyanalytics.com/documents/Mosaic_USA_Descriptions.pdf",
            "Simons"), this data is unavailable*/
    SIMONS_MOSAIC_USA_AUDIENCE_GUIDE("Simmons Mosaic® USA Audience Guide",
            "https://assets.simplyanalytics.com/documents/Mosaic_consumer_lifestyle_segmentation_system_Intro.pdf",
            "https://assets.simplyanalytics.com/documents/Mosaic_consumer_lifestyle_segmentation_system_Intro.pdf",
            "Simons"),

    //HEALTH VARIABLES
 /* HEALTH_VARIABLES_2019("2019 Health Variables",
          "https://assets.simplyanalytics.com/documents/EASILinks_MDBHealth.pdf",
          "https://assets.simplyanalytics.com/documents/EASILinks_MDBHealth.pdf",
          "Easi health variables"),
  NATIONAL_HEALTH_INTERVIEW_SURVEY_FOR_US_ADULTS_2018("http://www.cdc.gov/nchs/nhis/SHS/Tables.htm",
          "http://www.cdc.gov/nchs/nhis/SHS/Tables.htm",
          "http://www.cdc.gov/nchs/nhis/SHS/Tables.htm",
          "Easi health variables"),
  NATIONAL_HEALTH_INTERVIEW_SURVEY_FOR_US_CHILDREN_2018("http://www.cdc.gov/nchs/nhis/SHS/Tables.htm",
          "http://www.cdc.gov/nchs/nhis/SHS/Tables.htm",
          "http://www.cdc.gov/nchs/nhis/SHS/Tables.htm",
          "Easi health variables"),
  NATIONAL_HEALTH_INTERVIEW_SURVEY_FOR_US_DEATHS_2018("https://www.cdc.gov/nchs/data/nvsr/nvsr67/nvsr67_05.pdf",
          "https://www.cdc.gov/nchs/data/nvsr/nvsr67/nvsr67_05.pdf",
          "https://www.cdc.gov/nchs/data/nvsr/nvsr67/nvsr67_05.pdf",
          "Easi health variables"),
  NATIONAL_HEALTH_INTERVIEW_SURVEY_2009("https://www.cdc.gov/nchs/data/series/sr_10/sr10_249.pdf",
          "https://www.cdc.gov/nchs/data/series/sr_10/sr10_249.pdf",
          "https://www.cdc.gov/nchs/data/series/sr_10/sr10_249.pdf",
          "Easi health variables"), easi no longer available*/

    //APPLIED GEOGRAPHICAL SOLUTIONS (AGS)
    AGS_2019_HEALTH_CARE_VARIABLE_LIST("2019 AGS Health Care Variable List",
            "https://assets.simplyanalytics.com/documents/AGS-Health-Care-variable-list-2019.pdf",
            "https://assets.simplyanalytics.com/documents/AGS-Health-Care-variable-list-2019.pdf",
            "Ags"),
    AGS_2019_HEALTH_CARE_METHODOLOGY("2019 AGS Health Care Methodology",
            "https://assets.simplyanalytics.com/documents/AGS-Health-Care-Database-Methodology-2019.pdf",
            "https://assets.simplyanalytics.com/documents/AGS-Health-Care-Database-Methodology-2019.pdf",
            "Ags"),

    //USA FACTS COVID-19 OUTBREAK
    USAFACTS_COVID19_VISUALIZATIONS("USAFacts COVID-19 visualizations",
            "https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/",
            "https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/",
            "Usa facts"),

    //PUBLIC HEALTH AGENCY OF CANADA COVID-19
    PUBLIC_HEALTH_AGENCY_OF_CANADA_COVID19_ABOUT_PAGE("Public Health Agency of Canada COVID-19 About Page",
            "https://health-infobase.canada.ca/covid-19/dashboard/about.html",
            "https://health-infobase.canada.ca/covid-19/dashboard/about.html",
            "Canada facts");


    private String name;
    private String ref;
    private String verification_ref;
    private String category;

    DataDocumentationLinkEnum(String name, String ref, String verification_ref, String category) {
        this.name = name;
        this.ref = ref;
        this.verification_ref = verification_ref;
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public String getRef() {
        return ref;
    }

    public String getVerification_ref() {
        return verification_ref;
    }

    public String getCategory() {
        return category;
    }

    public static List<DataDocumentationLinkEnum> getLinksByCategory(String category) {
        List<DataDocumentationLinkEnum> documentList = new ArrayList<DataDocumentationLinkEnum>();
        for (DataDocumentationLinkEnum document : DataDocumentationLinkEnum.values()) {
            if (document.getCategory() != null && document.getCategory().equals(category)) {
                documentList.add(document);
            }
        }
        return documentList;
    }

    public static List<String> getAllCategories() {
        List<String> categoryList = new ArrayList<>();
        for (DataDocumentationLinkEnum document : DataDocumentationLinkEnum.values()) {
            if (!categoryList.contains(document.getCategory())) {
                categoryList.add(document.getCategory());
            }
        }
        return categoryList;
    }
}
